-- 1. Research Table (Create if missing)
create table if not exists public.research (
  id bigint generated by default as identity primary key,
  title text not null,
  summary text,
  content text,
  category text,
  author text,
  tags text[],
  image_url text,
  is_premium boolean default false,
  published_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enable RLS
alter table public.research enable row level security;
alter table public.news enable row level security;

-- 3. Cleanup Old Policies (To prevent errors if they exist)
drop policy if exists "Allow public read access" on public.research;
drop policy if exists "Allow public read access" on public.news;
drop policy if exists "Allow anon insert access" on public.research;
drop policy if exists "Allow anon insert access" on public.news;

-- 4. Create Policies (Allow Public Read/Write for demo)
create policy "Allow public read access" on public.research for select using (true);
create policy "Allow anon insert access" on public.research for insert with check (true);

create policy "Allow public read access" on public.news for select using (true);
create policy "Allow anon insert access" on public.news for insert with check (true);

-- 5. Insert Sample News (Current Time) - Ensures marker appears NOW
insert into public.news (title, summary, content, category, related_coin, sentiment_score, show_on_chart, source, published_at)
values 
('Bitcoin Breaks Resistance', 'Strong momentum observed.', 'Full content here.', 'Market', 'BTC', 0.85, true, 'TokenPost', now());
