-- Create Research Table (Missing)
create table if not exists public.research (
  id bigint generated by default as identity primary key,
  title text not null,
  summary text,
  content text,
  category text,
  author text,
  tags text[],
  image_url text,
  is_premium boolean default false,
  published_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS: Allow Read for Everyone (Fixes 403/404)
alter table public.research enable row level security;
create policy "Allow public read access" on public.research for select using (true);
create policy "Allow anon insert access" on public.research for insert with check (true);

-- Fix News Table Permissions (Fixes 403)
alter table public.news enable row level security;
create policy "Allow public read access" on public.news for select using (true); 
create policy "Allow anon insert access" on public.news for insert with check (true);

-- Create Index
create index if not exists research_category_idx on public.research (category);
