-- Create News Table
create table if not exists public.news (
  id bigint generated by default as identity primary key,
  title text not null,
  summary text,
  content text,
  category text,
  source text,
  image_url text,
  sentiment_score float,
  related_coin text,
  show_on_chart boolean default false,
  published_at timestamp with time zone default timezone('utc'::text, now()) not null,
  author text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Index for performance
create index if not exists news_related_coin_idx on public.news (related_coin);
create index if not exists news_show_on_chart_idx on public.news (show_on_chart);

-- Enable RLS
alter table public.news enable row level security;

-- Policy: Allow everyone to read
create policy "Enable read access for all users" on public.news for select using (true);

-- Policy: Allow insert/update for anon (for testing purposes, later restrict to authenticated)
create policy "Enable insert for anon" on public.news for insert with check (true);
create policy "Enable update for anon" on public.news for update using (true);
create policy "Enable delete for anon" on public.news for delete using (true);
